INSERT INTO users
    (id, first_name, last_name, email, phone, password, picture)
VALUES
    (DEFAULT, 'Bob', 'Saget','funny@videos.com', '784-231-9864', 'q!1BobSaget', 'https://pixel.nymag.com/imgs/daily/vulture/2018/07/12/splitsider/bob-saget-849135726.w700.h700.jpg'),
    (DEFAULT, 'Julia', 'Roberts','pretty@woman.com', '404-962-7843', 'q!1JuliaRoberts', 'https://akm-img-a-in.tosshub.com/indiatoday/images/story/201901/julia-roberts.jpeg?ZcYw5Tu5lwK8OAmXNBQzQMIno9xV6EU7'),
    (DEFAULT, 'Bob', 'Ross','happy@accident.com', '201-342-8649', 'q!1BobRoss', 'https://www.biography.com/.image/t_share/MTI1NDg4NTg2MDAxODA1Mjgy/bob-ross-promojpg.jpg'),
    (DEFAULT, 'Fred', 'Astaire','music@films.com', '442-893-6542', 'q!1FredAstaire', 'http://www.wikidancesport.com/Attachments/Legends/Fred%20Astaire/fred-astaire-ca-1941-everett.jpg'),
    (DEFAULT, 'Eliot', 'Ness','tommy@gun.com', '202-443-8956', 'q!1EliotNess', 'https://www.biography.com/.image/t_share/MTIwNjA4NjM0MDIyNDk1NzU2/eliot-ness-9542066-1-402.jpg');

INSERT INTO trips
    (id, name, city, country, start_date, end_date, creator_id, description)
VALUES
    (DEFAULT, 'Fun Times at the Beach', 'Miami', 'United States', '2018-03-18', '2019-03-28', 1, 'Spicy jalapeno meatloaf pork pariatur, commodo ham fatback filet mignon cupim. Bresaola brisket aute enim nulla meatloaf meatball tempor voluptate jerky doner duis tail chuck picanha. Pancetta in et deserunt qui ut. Ipsum ex landjaeger dolore ut, fugiat turducken tempor brisket duis. Beef ribs pork loin velit anim proident ribeye. Shoulder beef ribs hamburger commodo boudin ground round. Dolore cupim pork ut, commodo tenderloin shoulder cillum sausage swine.'),

    (DEFAULT, 'Big Apple Adventures', 'New York', 'United States', '2018-06-23', '2018-07-04', 2, 'Consequat shankle shoulder ullamco kevin voluptate. Flank ut bacon leberkas capicola ball tip minim id excepteur pork loin turducken strip steak frankfurter laboris dolor. Buffalo burgdoggen bacon short ribs nisi drumstick et salami velit kielbasa hamburger irure mollit jowl nulla. Pork belly in et, fatback ground round kielbasa salami fugiat. Velit cupim shankle capicola nostrud ham hock, doner sausage eu veniam turkey lorem labore nisi. Meatloaf irure chuck leberkas ut, elit non landjaeger drumstick incididunt.'),
    (DEFAULT, 'Sweating in the Heat', 'Austin', 'United States', '2019-02-11', '2019-02-18', 2, 'Labore aute aliquip filet mignon. Tongue dolor tail, cillum turkey flank porchetta fatback pig tempor cow. Consectetur voluptate pork, pancetta sirloin proident pastrami veniam officia. Spare ribs flank tail sausage.'),
    
    (DEFAULT, 'Pizza Bonanza', 'Chicago', 'United States', '2019-01-01', '2019-01-04', 3, 'Pork belly picanha cillum velit cow t-bone qui tri-tip duis nulla ut meatloaf capicola. Burgdoggen dolor bresaola ribeye beef short loin swine meatloaf commodo voluptate qui enim turkey adipisicing consequat. Ut lorem pancetta, sirloin in shank bresaola spare ribs non consequat tail ullamco incididunt. Voluptate cillum minim brisket corned beef pork loin, sirloin doner aute. Fugiat porchetta kielbasa, magna in voluptate pariatur rump id.'),
    (DEFAULT, 'Beantown Bonanza', 'Boston', 'United States', '2019-04-23', '2019-06-05', 3, 'Meatball short ribs shank, tenderloin fugiat irure tempor ut ipsum strip steak nostrud fatback. Kielbasa nisi ex lorem tongue. Cillum ex minim, laboris ut pancetta pastrami pork mollit capicola consequat pork chop anim. Veniam ut commodo excepteur. Tongue andouille ball tip, incididunt duis salami capicola veniam tenderloin ut sirloin voluptate est. Exercitation chuck voluptate, sunt tongue porchetta velit.'),
    (DEFAULT, 'Pastry Party', 'Paris', 'France', '2019-05-06', '2019-05-14', 3, 'Officia pork loin deserunt, in short ribs buffalo reprehenderit proident nisi incididunt. Elit dolor leberkas eu buffalo t-bone filet mignon in sint. Swine enim tempor, labore consectetur ham sirloin doner jerky capicola minim. Ut ex pancetta spare ribs magna kevin. Meatball dolore tempor frankfurter jerky corned beef sausage pork strip steak spare ribs.'),

    (DEFAULT, 'Coffee Exploring', 'Seattle', 'United States', '2019-04-17', '2019-04-23', 4, 'Quis tempor spare ribs id, sint ut jowl tongue ham hock. Tenderloin meatball velit nisi sausage mollit. Sunt tempor chuck shank non, ex et biltong ham aliqua sint fatback andouille pork loin consectetur. Hamburger veniam sed swine. Pork chop voluptate short ribs nisi. Cupim chuck enim boudin.'),
    (DEFAULT, 'Living on the Edge', 'Dukhan', 'Qatar', '2019-04-28', '2019-05-17', 4, 'Est frankfurter swine excepteur buffalo. Officia ham hock shank salami anim jerky. Culpa strip steak aliqua beef ribs, ground round in bacon mollit. Beef ribs capicola fatback dolore lorem fugiat filet mignon dolor ut in turducken et pork chop consectetur in. Hamburger salami dolore, deserunt spare ribs turducken ham hock sint pork belly anim pork loin alcatra cillum ex cupim.'),
    (DEFAULT, 'Fancy Car Festival', 'Dubai', 'United Arab Emirates', '2018-04-17', '2018-05-11', 4, 'Meatloaf bacon magna cupim. Bacon salami biltong excepteur, laboris tri-tip sunt picanha pork voluptate ham ullamco sirloin leberkas meatloaf. Biltong velit laborum ad tail sausage officia do landjaeger nulla. Nulla in qui, dolor pork belly pig corned beef filet mignon labore pariatur bresaola do beef ribs jerky. Spare ribs sunt salami kielbasa fugiat. Pariatur tri-tip bresaola nisi andouille labore beef qui buffalo id proident aliqua incididunt ham hock boudin. Spare ribs doner picanha ad, exercitation ea minim.'),
    (DEFAULT, 'Music Mashup', 'Nashville', 'United States', '2017-10-12', '2019-10-28', 4, 'Short ribs ribeye culpa in sunt non flank eiusmod id fatback bacon aliqua reprehenderit nisi exercitation. Shankle ea proident non t-bone. Consequat swine proident, laboris sunt irure lorem nisi ut doner. Sint velit magna filet mignon, jowl swine laboris ut ipsum elit. Sunt shank beef pork belly rump sed pork. Landjaeger sed spare ribs jowl consequat sausage anim ham hock shoulder laboris. Pig fatback consequat beef ribs cillum.'),

    (DEFAULT, 'Exploring the Depths', 'Jackson', 'United States', '2019-07-23', '2019-07-28', 5, 'Nostrud ea alcatra adipisicing, lorem eu consectetur boudin brisket burgdoggen. Beef proident cow laboris beef ribs in, meatball bresaola ullamco. Shoulder porchetta landjaeger, biltong cillum alcatra minim tail boudin voluptate commodo drumstick fatback picanha aliquip. Anim porchetta nisi, hamburger frankfurter dolore in picanha. Ball tip lorem ullamco magna chicken andouille. Ribeye eu picanha incididunt aute doner flank landjaeger exercitation swine.'),
    (DEFAULT, 'Mirth and Malice', 'Las Vegas', 'United States', '2019-09-12', '2019-09-18', 5, 'Pancetta non quis excepteur culpa flank ground round boudin frankfurter. Esse id ea nulla, prosciutto irure kevin burgdoggen aliqua tenderloin. Commodo sunt kielbasa sed consectetur lorem. Shankle pork belly eiusmod salami. Dolore labore irure, kielbasa ut turducken beef ribs ad deserunt chicken tongue nulla.'),
    (DEFAULT, 'Finest Vineyards', 'Napa', 'United States', '2019-11-14', '2019-11-16', 5, 'Corned beef pork loin frankfurter, fugiat in shank ground round dolor ullamco meatball tri-tip turkey ut. Labore anim minim adipisicing cillum, ribeye alcatra bacon ground round. Pancetta veniam frankfurter, in chuck turducken ground round aliquip pork ham hock exercitation tri-tip. Boudin shankle biltong duis burgdoggen spare ribs, pancetta bacon elit andouille rump laborum aute beef ribs. Dolore ullamco kielbasa minim chuck aliqua cupim ut shank turducken sunt spare ribs elit.'),
    (DEFAULT, 'Murderous Motions', 'St. Louis', 'United States', '2019-12-23', '2019-12-28', 5, 'Aliquip mollit sirloin dolore minim magna laboris qui quis dolor ut. Cillum nisi bacon dolore turducken cow tail voluptate buffalo incididunt ut meatball consectetur nostrud tri-tip. Sausage ut kielbasa venison short ribs turkey, esse pork chop non shank ground round. In frankfurter salami anim, pariatur dolore beef ribs qui occaecat nulla reprehenderit tempor commodo turkey ullamco. Tri-tip venison sunt pastrami, tempor shankle jowl enim bresaola.'),
    (DEFAULT, 'Devils Den', 'Durham', 'United States', '2020-02-12', '2020-02-28', 5, 'Aute ribeye culpa, jerky consequat ullamco capicola. Consectetur chuck officia leberkas rump. Capicola pork loin in excepteur, pastrami boudin kielbasa ea enim jowl pork belly kevin elit. Nisi lorem adipisicing, venison alcatra short loin ball tip duis rump pastrami fugiat pariatur in. Pork chop ut culpa meatball hamburger, pig t-bone sint turducken nulla cupim short loin exercitation meatloaf. Boudin jowl velit, sed beef turducken meatloaf eiusmod do.');